### PR TITLE
Akonsowski 562

### PR DESCRIPTION
**Pull request by akonsowski**
Made changes to the gulp file to make it easier to add new gulp functions inside of gulp tasks. Also added a gulp task to include a precision to make the css files generated IE friendly. This should fix the Bug in ozp-center [#562](https://github.com/ozone-development/ozp-center/issues/562)
@wski @bhalt @clarkjefcoat

### CODE REVIEW

**Comment by clarkjefcoat** [comment]
Are you sure you've committed everything?

```
$ npm run build

> icons@0.0.1 build /home/clark/ozp/ozp-icons
> gulp

module.js:328
    throw err;
    ^

Error: Cannot find module 'gulp-clean'
```

**Comment by akonsowski** [comment]
@clarkjefcoat try it now I've modified the package.json to include the missing packages

**Comment by akonsowski** [comment]
@clarkjefcoat  I've added the message

**Comment by clarkjefcoat** [comment]
@akonsowski - It builds successfully, but when I use it all of my icons are blank.

**Comment by clarkjefcoat** [comment]
Blank icon issue fixed with an additional commit.

:+1:

**Comment by akonsowski** [comment]
@SOAP1914 need another thumbs

**Comment by SOAP1914** [comment]
👍

**Pull request merged**
